apiVersion: v1
kind: Service
metadata:
  name: ueransim-gnb-svc
  labels:
    nf-type: ueransim-gnb
spec:
  selector:
    nf-type: ueransim-gnb
  ports:
    - protocol: UDP
      port: 4997
      targetPort: 4997 
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ueransim-gnb-depl
  labels:
    nf-type: ueransim-gnb
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: ueransim-gnb
  template:
    metadata:
      labels:
        nf-type: ueransim-gnb
    spec: 
      initContainers:
      - name: wait-for-amf-before-starup
        image: busybox:latest
        command:  ["/bin/sh", "-c"]   
        args:
          - echo wait-for-amf-before-starup;
            until nc -u -z amfran-svc 38412 > /dev/null; 
            do echo Waiting for amfran.; 
            sleep 2;
            done; echo amf started; sleep 45; echo done;
      containers:
        - name: ueransim-gnb
          image: "{{ .Values.ueransim.image.repository }}:{{ .Values.ueransim.image.tag }}"
          imagePullPolicy: {{ .Values.ueransim.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - cd /UERANSIM;
            ./build/nr-gnb -c config/open5gs-gnb.yaml;
            echo '********* Should not get here --> this means ueransim-gnb is broken!'
          volumeMounts:
          - name: ueransim-gnb-cmap
            mountPath: /UERANSIM/config/open5gs-gnb.yaml
            subPath: "open5gs-gnb.yaml"          
      volumes:
        - name: ueransim-gnb-cmap
          configMap:
            name: ueransim-gnb-cmap  
      imagePullSecrets:
        - name: {{ .Values.ueransim.image.imagePullSecrets }}