apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-cmap
  labels:
    epc-mode: amf
data:
  amf.yaml: |
    logger:
        file: /open5gs/amf.log
        #level: debug
        #domain: sbi
    amf:
        sbi:
        - addr: 0.0.0.0
          advertise: amf-svc
        ngap:
          dev: {{ .Values.k8s.interface }}
        guami:
          - plmn_id:
              mcc: {{ .Values.amf.mcc }}
              mnc: {{ .Values.amf.mnc }}
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: {{ .Values.amf.mcc }}
              mnc: {{ .Values.amf.mnc }}
            tac: {{ .Values.amf.tac }}
        plmn_support:
        - plmn_id:
            mcc: {{ .Values.amf.mcc }}
            mnc: {{ .Values.amf.mnc }}
          s_nssai:
          - sst: 1
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf0

    nrf:
      sbi:
        name: nrf-svc