apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: 27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      containers:
      - image: bitnami/mongodb:4.4.1-debian-10-r39
        name: open5gs-mongodb
        env:
        - name: DB_URI
          value: mongodb://mongodb-svc/open5gs #TODO
        command: 
          - /bin/bash
          - /add_admin.sh
        volumeMounts:
          - name: mongodb-cmap
            mountPath: /add_admin.sh
            subPath: add_admin.sh



        ports:
        - containerPort: 27017 #TODO 
          name: mongodb
        
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db



      volumes:
      - name: mongodb-cmap
          configMap:
            name: mongodb-cmap
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodes.cluster }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi