apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-cmap
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
        file: /open5gs/nrf.log
        
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    nrf:
        sbi:
          addr: 0.0.0.0