apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-cmap
  labels:
    nf-type: nssf
data:
  nssf.yaml: |
    logger:
        file: /open5gs/nssf.log

    nssf:
      sbi:     
      - addr: 0.0.0.0
        advertise: nssf-svc
      
      nsi:
      - addr: nrf-svc
        port: 80
        s_nssai:
          sst: 1        
    nrf:
     sbi:
      name: nrf-svc