apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-cmap
  labels:
    nf-type: pcf
data:
  pcf.yaml: |
    logger:
        file: /open5gs/pcf.log
    
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
    
    db_uri: mongodb://mongodb-5g-svc:27017/open5gs

    pcf:
      sbi:     
      - addr: 0.0.0.0
        advertise: pcf-svc
    nrf:
     sbi:
      name: nrf-svc 