apiVersion: v1
kind: Service
metadata:
  name: smf-svc
  labels:
    nf-type: smf
spec:
  selector:
    nf-type: smf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: smf-depl
  labels:
    nf-type: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: smf
  template:
    metadata:       
      labels:
        nf-type: smf
    spec:   
      containers:
      - name: smf
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - cd /open5gs;
          ./install/bin/open5gs-smfd -c /open5gs/config-map/smf.yaml;
          echo '********* Should not get here --> this means SMF is broken!'
        volumeMounts:
          - name: smf-cmap
            mountPath: /open5gs/config-map/smf.yaml
            subPath: "smf.yaml"                                       
      imagePullSecrets:
        - name: {{ .Values.open5gs.image.imagePullSecrets }}
      volumes:
        - name: smf-cmap
          configMap:
            name: smf-cmap  
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodes.cluster }}
