apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-cmap
  labels:
    nf-type: udm
data:
  udm.yaml: |
    logger:
        file: /open5gs/udm.log

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
    
    udm:
      sbi:   
      - addr: 0.0.0.0
        advertise: udm-svc
    nrf:
     sbi:
      name: nrf-svc