apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-cmap
  labels:
    nf-type: udr
data:
  udr.yaml: |
    logger:
        file: /open5gs/udr.log

    db_uri: mongodb://mongodb-5g-svc:27017/open5gs

    udr:
      sbi:
      - addr: 0.0.0.0
        advertise: udr-svc

    nrf:
     sbi:
      name: nrf-svc  