apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  labels:
    nf-type: webui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    nf-type: webui
---
apiVersion: v1
kind: Service
metadata:
  labels:
    nf-type: webui
  name: open5gs-webui-nodeport
spec:
  type: NodePort
  selector:
    nf-type: webui
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 3000 # Pod port
      nodePort: 30080 # Node port
  sessionAffinity: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-webui 
  labels:
    nf-type: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: webui
  template:
    metadata:
      labels:
        nf-type: webui
    spec:
      containers:
      - name: webui
        imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
        image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"      
        env:
        - name: DB_URI
          value: mongodb://mongodb-5g-svc:27017/open5gs
        - name: NODE_ENV
          value: "production"  
        - name: HOSTNAME
          value: '0.0.0.0'  
      imagePullSecrets:
        - name: {{ .Values.webui.image.imagePullSecrets }}
      volumes:
        - name: account-creation
          configMap:
            name: mongodb-cmap