# Default values for 5gnetwork.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: gitlab-registry.imt-atlantique.fr/b20stuck/mise-en-place-d-un-reseau-5g-dynamique/open5gs
    pullPolicy: IfNotPresent
    tag: "v0.1"
    imagePullSecrets: gitlabimta

ueransim: # NEW 
  image:
    repository: gitlab-registry.imt-atlantique.fr/b20stuck/mise-en-place-d-un-reseau-5g-dynamique/ueransim
    pullPolicy: IfNotPresent
    tag: "v0.4"
    imagePullSecrets: gitlabimta
  ue:
    initialMSISDN: '0000000001'

webui:
  image:
    repository: gitlab-registry.imt-atlantique.fr/b20stuck/mise-en-place-d-un-reseau-5g-dynamique/open5gs-webui
    pullPolicy: IfNotPresent
    tag: "v0.1"
    imagePullSecrets: gitlabimta
  initContainer:
    image:
      repository: bitnami/mongodb
      pullPolicy: IfNotPresent
      tag: "latest"

# Data Network Names
dnn: internet
dnn2: mecnet

amf:
  mcc: '001'
  mnc: '01'
  tac: '1'

# Primary/Native kubernetes interface
k8s:
 interface: eth0

# Mongodb is depolyed with bitnami cf chart.yaml
mongodb:
  initdbScriptsConfigMap: "mongodb-cmap"
  nodeSelector:
    kubernetes.io/hostname: "computer2-5g"
  service:
    nameOverride: "mongodb-5g-svc"
  auth:
    enabled: false
  persistence:
    enabled: true
    resourcePolicy: "keep"
    storageClass: "manual"
