# Default values for 5gnetwork.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: gitlab-registry.imt-atlantique.fr/b20stuck/mise-en-place-d-un-reseau-5g-dynamique/open5gs
    pullPolicy: IfNotPresent
    tag: "v0.1"
    imagePullSecrets: gitlabimta

ueransim: # NEW 
  gnb:
    image:
      repository: gitlab-registry.imt-atlantique.fr/b20stuck/mise-en-place-d-un-reseau-5g-dynamique/ueransim
      pullPolicy: IfNotPresent
      tag: "v0.4"
      imagePullSecrets: gitlabimta

webui:
  image:
    repository: gitlab-registry.imt-atlantique.fr/b20stuck/mise-en-place-d-un-reseau-5g-dynamique/open5gs-webui
    pullPolicy: IfNotPresent
    tag: "v0.1"
    imagePullSecrets: gitlabimta

# Data Network Names
dnn: internet
dnn2: mecnet

amf:
  mcc: '001'
  mnc: '01'
  tac: '1'

# Where to deploy the NFs
nodes:
  cluster: 'computer2-5g'
  mec: 'computer3-5g'

# Primary/Native kubernetes interface
k8s:
 interface: eth0

# Mongodb is depolyed with bitnami cf chart.yaml
mongodb:
  service:
    nameOverride: "mongodb-5g-svc"
  auth:
    enabled: false
  persistence:
    enabled: false
